[project]
name = "olmo-debug"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bloom",
    "vllm>=0.13.0",
]

[tool.uv.sources]
bloom = { path = "../bloom", editable = true }
